# Site
name: "Góc nhìn HSE"
title: "Blog An toàn lao động"
description: "Chia sẻ kiến thức, kinh nghiệm về an toàn và kỹ thuật."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'G-TR8LWBC5BL'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  chienhse:
    name: Chien
    display_name: ChienHSE
    gravatar: 
    email: work.chien03@gmail.com
    web: https://chienhse.vn
    twitter: 
    description: "Kỹ sư an toàn lao động. Ghi chép và hệ thống hóa kiến thức chuyên môn."
 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
 # - jekyll-archives
    
# Archives
#jekyll-archives:
#  enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
